-- local config = {}
-- local main_font = "TerminessTTF Nerd Font 10"
-- local tags_list_font = "RobotoMono Nerd Font 9"
-- local color_pink = "#F8708C"
-- local color_gray = "#262525"
-- function config.config_theme(theme)
--     theme.font = main_font
--     theme.taglist_font = tags_list_font
--     theme.bg_normal = color_gray
--     theme.fg_normal = color_pink
--     theme.border_color_active = color_pink
-- end
-- return config
